#include "./../var.h"

#ifndef __INTERFACE_BC_H
#define __INTERFACE_BC_H

#define INTERFACE_BC_WEST_PERIO (tx == 0)
#define INTERFACE_BC_WEST_BLOCK (tx == 0 && x != 0)
#define INTERFACE_BC_EAST_PERIO (tx == (BLOCK_NX - 1))
#define INTERFACE_BC_EAST_BLOCK (tx == (BLOCK_NX - 1) && x != (NX - 1))

#define INTERFACE_BC_SOUTH_PERIO (ty == 0)
#define INTERFACE_BC_SOUTH_BLOCK (ty == 0 && y != 0)
#define INTERFACE_BC_NORTH_PERIO (ty == (BLOCK_NY - 1))
#define INTERFACE_BC_NORTH_BLOCK (ty == (BLOCK_NY - 1) && y != (NY - 1))

#ifdef BC_X_WALL
#define INTERFACE_BC_WEST INTERFACE_BC_WEST_BLOCK
#define INTERFACE_BC_EAST INTERFACE_BC_EAST_BLOCK
#endif
#ifdef BC_X_PERIODIC
#define INTERFACE_BC_WEST INTERFACE_BC_WEST_PERIO
#define INTERFACE_BC_EAST INTERFACE_BC_EAST_PERIO
#endif

#ifdef BC_Y_WALL
#define INTERFACE_BC_SOUTH INTERFACE_BC_SOUTH_BLOCK
#define INTERFACE_BC_NORTH INTERFACE_BC_NORTH_BLOCK
#endif
#ifdef BC_Y_PERIODIC
#define INTERFACE_BC_SOUTH INTERFACE_BC_SOUTH_PERIO
#define INTERFACE_BC_NORTH INTERFACE_BC_NORTH_PERIO
#endif

#endif